site_name: Contextually
site_url: https://flowcontextually.github.io/docs/
site_author: dpwanjala
site_description: >-
  The Universal Computational Fabric. A declarative, multi-stage automation
  platform where work retains its full context as it flows between different
  tools, people, and AI agents.

# Repository
repo_name: flowcontextually/cx-shell
repo_url: https://github.com/flowcontextually/cx-shell
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2025 Contextually

# Theme Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

nav:
  - "Overview": "index.md"
  - "Tutorials":
      - "Getting Started": "tutorials/getting-started.md"
      - "Your First Agentic Translation": "tutorials/first-agent-session.md"
      - "Compiling a Blueprint": "tutorials/compiling-a-blueprint.md"
  - "How-To Guides":
      - "Use the `cx` Agent": "how-to/use-the-agent.md"
      - "Manage Background Processes": "how-to/manage-processes.md"
      - "Build In-Terminal Pipelines": "how-to/building-pipelines.md"
      - "Managing Your Workspace": "how-to/managing-your-workspace.md"
      - "Connect to a Database": "how-to/connect-database.md"
      - "Connect to a REST API": "how-to/connect-rest-api.md"
      - "Packaging an Application": "how-to/packaging-an-application.md"
  - "Cookbook":
      - "Automating a Daily Report": "cookbook/daily-reporting-workflow.md"
      - "Creating an On-Demand Data API": "cookbook/on-demand-data-api.md"
  - "Reference":
      - "CLI Commands ($)": "reference/cli.md"
      - "Interactive Shell (cx>)": "reference/repl.md"
      - "Power User Tools": "reference/power-tools.md"
      - "Blueprint Specification": "reference/blueprint-spec.md"
  - "Concepts":
      - "The Agentic Shell": "concepts/agentic-shell.md"
      - "The Blueprint Ecosystem": "concepts/blueprint-ecosystem.md"
      - "The Application Ecosystem": "concepts/application-ecosystem.md"
      - "The Shell as a Workspace IDE": "concepts/shell-as-ide.md"
      - "Thinking in Pipelines": "concepts/thinking-in-pipelines.md"
