name: Deploy Documentation to GitHub Pages

on:
  # Run this workflow automatically on every push to the `main` branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

permissions:
  contents: write # to checkout the code

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Build and Deploy Documentation
        # This command builds the site and pushes the result to the gh-pages branch.
        # It uses the GITHUB_TOKEN with the permissions we granted above.
        run: mkdocs gh-deploy --force --clean
